{
 "title": "each_symbol",
 "time": { "from": "2022-01-01T00:00:00.000Z", "to": "2022-10-21T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": "SELECT UPPER(table_name) AS list\nFROM information_schema.tables\nWHERE table_schema='public'"
   }
  ]
 },
 "panels": [
  {
   "title": "${Symbol} Month High/Low",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT close\nFROM ${Symbol}\nORDER BY time DESC\nLIMIT 31"
    }
   ]
  },
  {
   "title": "${Symbol} Latest",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT close, time\nFROM ${Symbol}\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": {
    "content": "<font size=\"10\">${Symbol}</font> \n<p align=\"center\">"
   }
  },
  {
   "title": "Crypto Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(table_name) AS list\nFROM information_schema.tables\nWHERE table_schema='public'"
    }
   ]
  },
  {
   "title": "${Symbol} Close ",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT time,\nclose\nFROM ${Symbol}\n"
    }
   ]
  },
  {
   "title": "${Symbol} 6 Month Volume",
   "type": "barchart",
   "description": "Hover over bar for volume info.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT time,\nvolume\nFROM ${Symbol}\nORDER BY time DESC\nLIMIT 186"
    }
   ]
  },
  {
   "title": "${Symbol} Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM ${Symbol}\nORDER BY time desc"
    }
   ]
  }
 ]
}